/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"

@class SBApplication;

@interface SBApplicationIcon : SBLeafIcon {
	SBApplication* _app;
}
-(id)initWithApplication:(id)application;
-(void)dealloc;
-(id)application;
-(id)generateIconImage:(int)image;
-(id)displayName;
-(id)leafIdentifier;
-(BOOL)shouldEllipsizeLabel;
-(id)tags;
-(id)_automationID;
-(BOOL)launchEnabled;
-(void)launch;
-(void)setBadge:(id)badge;
-(void)_setBadge:(id)badge;
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
-(id)applicationBundleID;
@end

