/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "UITextFieldDelegate.h"

@class SBFolderTitleLabel, SBFolderTextField, SBFolderShadowView, SBFolderIconListView, SBFolder;

@interface SBFolderView : UIView <UITextFieldDelegate> {
	SBFolder* _folder;
	SBFolderTitleLabel* _label;
	SBFolderShadowView* _shadowView;
	SBFolderTextField* _textField;
	SBFolderIconListView* _iconListView;
	BOOL _isEditing;
	unsigned _rows;
	XXStruct_9ihRqB _notchInfo;
}
-(id)initWithRows:(unsigned)rows notchInfo:(XXStruct_9ihRqB)info;
-(float)slideHeight;
-(unsigned)rows;
-(void)setIconListView:(id)view;
-(id)iconListView;
-(void)dealloc;
-(void)setFolder:(id)folder;
-(void)setFolderName:(id)name;
-(void)setIsEditing:(BOOL)editing animated:(BOOL)animated;
-(void)enableShiftForFolderTextFieldAfterBeginEditing;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldClear:(id)textField;
-(NSRange)textField:(id)field willChangeSelectionFromCharacterRange:(NSRange)characterRange toCharacterRange:(NSRange)characterRange3;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)setBackgroundAlpha:(float)alpha;
-(id)editTitleField;
@end

