/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBPasscodeAlertItem, NSString, NSDate, SBPasscodeComplianceAlertItem;

@interface SBPasscodeController : NSObject {
	SBPasscodeAlertItem* _passcodeAlertItem;
	int _mode;
	NSString* _previousPasscode;
	NSString* _newPasscode;
	int _unlockScreenType;
	SBPasscodeComplianceAlertItem* _complianceAlertItem;
	NSDate* _forcedComplianceDate;
}
+(id)sharedInstance;
-(void)dealloc;
-(void)forceUserToChangePasscode;
-(void)_passwordEntered:(id)entered;
-(void)_userWantsToComplyNow:(BOOL)complyNow;
-(void)_abort;
-(void)checkPasscodeCompliance;
@end

