/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface SBSMSManager : NSObject {
	int _badgeState;
}
@property(assign, nonatomic) int badgeState;
+(id)sharedSMSManager;
-(void)messageSent:(id)sent;
-(void)messageSendError:(id)error;
-(void)messageReceived:(id)received;
-(id)init;
-(id)badgeNumberOrString;
-(void)setBadge:(id)badge badgeState:(int)state;
-(void)updateSMSBadgeToState:(int)state;
-(void)updateSMSBadges;
-(void)markMessageAsRead:(id)read;
@end

