/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct {
	BOOL _field1;
	BOOL _field2;
	BOOL _field3;
	float _field4;
	int _field5;
	float _field6;
} XXStruct_3B_lsC;







typedef struct SBApplicationTimes {
	double _field1;
	double _field2;
	double _field3;
	double _field4;
	double _field5;
	double _field6;
	double _field7;
} SBApplicationTimes;


typedef struct _MISProfile* MISProfileRef;

typedef struct {
	unsigned _field1[8];
} XXStruct_kUSYWB;









typedef struct {
	unsigned char voicemailAvailable;
	int voicemailCount;
	long long voicemailID;
} XXStruct_EX3dgA;




typedef struct {
	int _field1;
	BOOL _field2;
	BOOL _field3;
	BOOL _field4;
	BOOL _field5;
	double _field6;
} XXStruct_fhKmAA;





typedef struct {
	int direction;
	CGRect rect;
} XXStruct_9ihRqB;


